server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qr_attendance_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
  flyway:
    locations: classpath:db/migration,classpath:seed